### ISSUE TITLE
Center align the images of the cards

### ISSUE THREAD

**Issue by Prakharsharma2206** [Prakharsharma2206/Hacktober22#11]
The card present has an alignment issue in it. 
Center align the images in the given div

**Comment by sidmadke** [comment]
@Prakharsharma2206 I want to work on this issue.

**Comment by Prakharsharma2206** [comment]
Assigned it to you

**Comment by sidmadke** [comment]
@Prakharsharma2206 I have made PR, please review it and do consider it for merge😇
