### ISSUE TITLE
Dynamically rendering card details

### ISSUE THREAD

**Issue by SameepAher** [Prakharsharma2206/Hacktober22#14]
Currently all the information in the card is hard coded. Hence, the code looks very lengthy and repetitive.
I will fix this issue by dynamically rendering all the cards and their components. This will make the code look cleaner, a lot more understandable and non-repetitive.

If you like this idea, please assign this issue to me.

**Comment by Prakharsharma2206** [comment]
Sounds perfect to me, just try to make a JSON file over there to render the Information with the help of map function.
After doing this just comment here done, so that I can update the ReadMe.md and Contribute.md files.

**Comment by Prakharsharma2206** [comment]
Assigned the issue to you @SameepAher

**Comment by SameepAher** [comment]
Done.
PR has been created

**Comment by SameepAher** [comment]
Sorry, the previous PR had some issues.
A new PR has been created for the same.
