### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by sidharth2603** [Prakharsharma2206/Hacktober22#21]

**Comment by sidharth2603** [comment]
As a part of Open Source project, there should be a Code of Conduct in each repository that should be followed while contributing to the project.
The code of conduct for this repository is missing, I would like to contribute to the same, please assign me this issue

**Comment by Prakharsharma2206** [comment]
Hacktober Code of Conduct is a necessity for every Repo so it is not necessary for this.
