### ISSUE TITLE
Countdown timer using js

### ISSUE THREAD

**Issue by sidhrth04** [Prakharsharma2206/Hacktober22#6]
@Prakharsharma2206  , Hey please let me contribute with countdown timer using js on profile cards made with html and css
it will be very helpful
thank you.

**Comment by shubhkush57** [comment]
I would like to contribute to this repo, Can you assign me this issue please.............

**Comment by Prakharsharma2206** [comment]
> @Prakharsharma2206 , Hey please let me contribute with countdown timer using js on profile cards made with html and css it will be very helpful thank you.

Please either add a card or improvise by creating a similar sort of section. A count down timer will not be relevant to this repo
